# 服务
services:

  nginx:
    image: ${MIRROR_REGISTRY_REPO}nginx:1.23.3-alpine
    restart: on-failure
    hostname: nginx
    ports:
      - 8080:80
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./dist:/usr/share/nginx/html
      # - ./.output/public:/usr/share/nginx/html # npm run generate
    environment:
      - TZ=${TIME_ZONE:-Asia/Shanghai}
